apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv-volume0
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/vitocianchini/Documents/ACES/NATS_conversion/ACES.Metrics-Handler-main/pvs/prometheus/0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv-volume1
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/vitocianchini/Documents/ACES/NATS_conversion/ACES.Metrics-Handler-main/pvs/prometheus/1"