apiVersion: v1
kind: Service
metadata:
  labels:
    app: notebook
  name: notebook
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    app: notebook
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notebook
  name: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
        - env:
            - name: CHOWN_HOME
              value: "yes"
            - name: CHOWN_HOME_OPTS
              value: -R
            - name: GRANT_SUDO
              value: "yes"
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
            - name: JUPYTER_TOKEN
              value: "horse"
            - name: NB_GID
              value: "1000"
            - name: NB_USER
              value: "horse"
          image: pkapsalismartel/notebook:v0.10
          name: notebook
          ports:
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /home/horse
              name: notebook-claim0
          workingDir: /home/horse
      hostname: notebook
      restartPolicy: Always
      volumes:
        - name: notebook-claim0
          persistentVolumeClaim:
            claimName: notebook-claim0
status: {}