version: "3"
services:
  memgraph-platform:
    image: "memgraph/memgraph-platform"
    container_name: memgraph-platform
    hostname: memgraph-platform
    restart: always
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    environment:
      MEMGRAPH: --log-level=TRACE
    entrypoint: ["/usr/bin/supervisord"]

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    hostname: timescaledb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aces
      POSTGRES_PASSWORD: aces
      POSTGRES_DB: aces
    volumes:
      - timescaledb:/var/lib/postgresql/data
volumes:
  mg_lib:
  mg_log:
  mg_etc:
  timescaledb: