apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: timescaledb
  name: timescaledb
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
