apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-pv-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/vitocianchini/Documents/ACES/NATS_conversion/ACES.Metrics-Handler-main/pvs/neo4j"