apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-kafka-adapter
  name: prometheus-kafka-adapter
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: prometheus-kafka-adapter
status:
  loadBalancer: {}