apiVersion: v1
kind: Service
metadata:
  name: aces-w3-alibaba-ml-upmv1-svc
spec:
  selector:
    app: aces-w3-alibaba-ml-upmv1
  ports:
  - port: 8081
    targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aces-w3-alibaba-ml-upmv1
spec:
  # run as much your system supports
  replicas: 3
  selector:
    matchLabels:
      app: aces-w3-alibaba-ml-upmv1
  template:
    metadata:
      labels:
        app: aces-w3-alibaba-ml-upmv1
    spec:
      containers:
      - name: aces-w3-alibaba-ml-upm-cont
        image: ayahyaou/aces_wp3_alibaba_ml_upm:v2
        ports:
        - containerPort: 8081
