apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mc
  name: mc
  namespace: minio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/mc-default: "true"
        app: mc
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - ' /usr/bin/mc config host add horse http://minio admin martel2024; /usr/bin/mc mb horse/prefect; /usr/bin/mc mb horse/emdc; /usr/bin/mc policy set public horse/prefect; /usr/bin/mc policy set public horse/emdc; exit 0; '
          image: minio/mc
          name: mc
          resources: {}
      restartPolicy: Always
status: {}